#!/usr/bin/env python

import sys
import jenkins
import urllib
import yaml
import subprocess

ubuntu_distro = {'fuerte': ['precise'],
                 'groovy': ['precise']}
arch = ['amd64', 'i386']

def call(command, envir=None):
    print command
    helper = subprocess.Popen(command.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True, env=envir)
    res, err = helper.communicate()
    print str(res)
    print str(err)
    if helper.returncode != 0:
        print "Failed to execute command '%s'"%command
    return res


# Schedule all devel jobs on Jenkins
def main():
    if len(sys.argv) != 2:
        print "Usage: %s ros_distro"%(sys.argv[0])
        sys.exit(0)
    ros_distro = sys.argv[1]
    
    # parse the devel distro file
    print "Parsing devel yaml file for %s"%ros_distro
    f = urllib.urlopen('https://raw.github.com/ros/rosdistro/master/releases/%s-devel.yaml'%ros_distro)
    devel = yaml.load(f.read())['repositories']

    # create all jobs
    for s, conf in devel.iteritems():
        for u in ubuntu_distro[ros_distro]:
            for a in arch:
                call("./run_jenkins_vcs %s %s %s wim@hidof.com %s %s %s devel %s %s"%(u, a, ros_distro+'-'+s, conf['type'], conf['url'], conf['version'], ros_distro, s))

    print devel




if __name__ == "__main__":
    main()
