#!/usr/bin/env python

import sys
import jenkins
import urllib
import yaml
import subprocess

ubuntu_distro = {'fuerte': ['precise'],
                 'groovy': ['precise']}
arch = ['amd64']

def call(command, envir=None):
    print command
    helper = subprocess.Popen(command.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True, env=envir)
    res, err = helper.communicate()
    print str(res)
    print str(err)
    if helper.returncode != 0:
        print "Failed to execute command '%s'"%command
    return res


# Schedule all doc jobs on Jenkins
def main():
    if len(sys.argv) != 3:
        print "Usage: %s ros_distro file"%(sys.argv[0])
        print "Ex: %s fuerte dry-doc"%(sys.argv[0])
        sys.exit(0)
    ros_distro = sys.argv[1]
    file_ext = sys.argv[2]
    
    # parse the devel distro file
    print "Parsing doc yaml file for %s"%ros_distro
    f = urllib.urlopen('https://raw.github.com/ros/rosdistro/master/releases/%s-%s.yaml'%(ros_distro, file_ext))
    devel = yaml.load(f.read())['repositories']

    # create all jobs
    for s, conf in devel.iteritems():
        for u in ubuntu_distro[ros_distro]:
            for a in arch:
                if conf['type'] == 'svn':
                    conf['version'] = 'dummy'
                #call("./run_jenkins_vcs %s %s %s eitan@hidof.com %s %s %s doc %s %s"%(u, a, 'doc-'+ros_distro+'-'+s, conf['type'], conf['url'], conf['version'], ros_distro, s))
                call("./run_jenkins_now.py %s %s %s eitan@hidof.com doc %s %s"%(u, a, ros_distro+'-'+s, ros_distro, s))






if __name__ == "__main__":
    main()
