#!/usr/bin/env python

import sys
import jenkins
import urllib
import yaml
import subprocess
import os

ubuntu_distro = {'fuerte': ['precise'],
                 'groovy': ['precise']}
arch = ['amd64']

def call(command, envir=None):
    print command
    helper = subprocess.Popen(command.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True, env=envir)
    res, err = helper.communicate()
    print str(res)
    print str(err)
    if helper.returncode != 0:
        print "Failed to execute command '%s'"%command
    return res


# Schedule all doc jobs on Jenkins
def main():
    if len(sys.argv) != 3:
        print "Usage: %s ros_distro file"%(sys.argv[0])
        print "Ex: %s fuerte folder_name"%(sys.argv[0])
        sys.exit(0)
    ros_distro = sys.argv[1]
    file_dir = sys.argv[2]

    rosinstall_files = []
    for ls_file in os.listdir(file_dir):
        if ls_file.endswith(".rosinstall"):
            rosinstall_files.append(os.path.splitext(os.path.basename(ls_file))[0])

    for s in rosinstall_files:
        if s.endswith('depends'):
            continue

        for u in ubuntu_distro[ros_distro]:
            for a in arch:
                call("./run_jenkins_now.py %s %s %s eitan@hidof.com doc %s %s"%(u, a, ros_distro+'-'+s, ros_distro, s))

if __name__ == "__main__":
    main()
