#!/usr/bin/env python

import sys
import jenkins
import urllib
import yaml
import datetime

CONFIG_PATH_LOCAL = '/home/willow/hds.xml'
CONFIG_PATH = 'http://wgs24.willowgarage.com/hudson-html/hds.xml'
SERVER = 'http://jenkins.willowgarage.com:8080/'

# Schedule a set of jobs in Jenkins
def main():
    if len(sys.argv) < 6:
        print "Usage: %s ubuntu_distro arch job_name email script [script_args]"%(sys.argv[0])
        sys.exit(0)
    
    # open template xlm file
    f = urllib.urlopen('https://raw.github.com/willowgarage/buildfarm/master/templates/jenkins_template.xml')
    job_xml = f.read()

    # open trigger file
    f = urllib.urlopen('https://raw.github.com/willowgarage/buildfarm/master/templates/jenkins_conf.yaml')
    jc = yaml.load(f)

    # get arguments
    params = {}
    params['UBUNTU_DISTRO'] = sys.argv[1]
    params['ARCH'] = sys.argv[2]
    params['EMAIL'] = sys.argv[4]
    params['SCRIPT'] = sys.argv[5]
    params['NODE'] = params['SCRIPT']
    params['SCRIPT_ARGS'] = ' '.join(sys.argv[6:])
    params['TRIGGER'] = jc['triggers']['none']
    params['VCS'] = jc['vcs']['none']
    params['TIME'] = datetime.datetime.now()

    # replace @xxx@ in template file
    for key, value in params.iteritems():
        job_xml = job_xml.replace("@%s@"%key, value)

    # create hudson instance                                                                                                            
    try:
        with open(CONFIG_PATH_LOCAL) as f:
            info = f.read().split(',')
    except:
        info = urllib.urlopen(CONFIG_PATH).read().split(',')
    jenkins_instance = jenkins.Jenkins(SERVER, info[0], info[1])
    
    # schedule a new job
    job_name = sys.argv[3]
    job_name = "%s-%s-%s-%s"%(params['SCRIPT'], job_name, params['UBUNTU_DISTRO'], params['ARCH'])
    if jenkins_instance.job_exists(job_name):
        jenkins_instance.reconfig_job(job_name, job_xml)
        print "Reconfigured job %s"%job_name
    else:
        jenkins_instance.create_job(job_name, job_xml)
        print "Created job %s"%job_name
    jenkins_instance.build_job(job_name)
    print "Started job %s"%job_name
    print "When the test finishes, you will receive an email at %s"%params['EMAIL']

if __name__ == "__main__":
    main()
