#!/usr/bin/env python
from test_repositories import *



def main():
    if len(sys.argv) != 2:
        print "Usage: %s ros_distro repository_name"%sys.argv[0]
        raise BuildException("Wrong number of parameters for devel script")

    ros_distro = args[0]
    repositories = args[1:]
    workspace = os.environ['WORKSPACE']    
    print "Running devel test on distro %s and repositories %s"%(ros_distro, ', '.join(repositories))

    test_repositories(ros_distro, repositories, workspace, use_devel_repo=True, test_depends_on=False)



if __name__ == '__main__':
    # global try
    try:
        main()
        print "devel script finished cleanly"

    # global catch
    except BuildException as ex:
        print ex.msg

    except Exception as ex:
        print "devel script failed. Check out the console output above for details."
        raise ex
