#!/usr/bin/env python
import os
import sys
import rosdistro
import yaml
import subprocess
import urllib
import datetime
import fnmatch
from xml.etree.ElementTree import ElementTree


def call(command, envir=None):
    print "Executing command '%s'"%command
    helper = subprocess.Popen(command.split(' '), 
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE, 
                              close_fds=True, env=envir)
    res, err = helper.communicate()
    print str(res)
    print str(err)
    if helper.returncode != 0:
        msg = "Failed to execute command '%s'"%command
        print "/!\  %s"%msg
        raise BuildException(msg)
    return res


def get_dependencies(stack_folder):
    # get the stack dependencies
    print "Get the dependencies of stack in folder %s"%stack_folder
    try:
        print "Parsing stack.xml..."
        root = ElementTree(None, os.path.join(stack_folder, 'stack.xml'))
        stack_dependencies = [d.text for d in root.findall('depends')]
        system_dependencies = [d.text for d in root.findall('build_depends')]
        print "Stack Dependencies: %s"%(' '.join(stack_dependencies))
        print "System Dependencies: %s"%(' '.join(system_dependencies))
        return stack_dependencies + system_dependencies
    except Exception, ex:
        raise BuildException("Failed to parse stack.xml of stack in folder %s"%stack_folder)


def get_ros_env(setup_file):
    ros_env = os.environ
    print "Retrieve the ROS build environment by sourcing %s"%setup_file
    command = ['bash', '-c', 'source %s && env'%setup_file]
    proc = subprocess.Popen(command, stdout = subprocess.PIPE)
    for line in proc.stdout:
        (key, _, value) = line.partition("=")
        ros_env[key] = value.split('\n')[0]
    proc.communicate()
    if proc.returncode != 0:
        msg = "Failed to source %s"%setup_file
        print "/!\  %s"%msg
        raise BuildException(msg)
    print "ROS environment: %s"%str(ros_env)
    return ros_env


class RosDep:
    def __init__(self, ros_distro):
        self.r2a = {}
        self.a2r = {}
        self.env = os.environ
        self.env['ROS_DISTRO'] = ros_distro

        # Initialize rosdep database
        print "Ininitalize rosdep database"
        call("apt-get install --yes lsb-release python-rosdep")
        call("rosdep init", self.env)
        call("rosdep update", self.env)

    def to_apt(self, r):
        if r in self.r2a:
            return self.r2a[r]
        else:
            a = call("rosdep resolve %s"%r, self.env).split('\n')[1]
            print "Rosdep %s resolved into %s"%(r, a)
            self.r2a[r] = a
            self.a2r[a] = r
            return a

    def to_stack(self, a):
        if not a in self.a2r:
            print "%s not in apt-to-rosdep cache"%a
        return self.a2r[a]


def copy_test_results(workspace, buildspace):
    print "Preparing xml test results"
    try:
        os.makedirs(os.path.join(workspace, 'test_results'))
        print "Created test results directory"
    except:
        pass
    os.chdir(os.path.join(workspace, 'test_results'))
    print "Copy all test results"
    count = 0
    for root, dirnames, filenames in os.walk(os.path.join(buildspace, 'test_results')):
        for filename in fnmatch.filter(filenames, '*.xml'):
            call("cp %s %s/test_results/"%(os.path.join(root, filename), workspace))
            count += 1
    if count == 0:
        print "No test results, so I'll create a dummy test result xml file"
        call("cp %s %s"%(os.path.join(workspace, 'buildfarm/templates/junit_dummy_ouput_template.xml'),
                         os.path.join(workspace, 'test_results/')))


class BuildException(Exception):
    def __init__(self, msg):
        self.msg = msg

def main():

    if len(sys.argv) != 3:
        print "Usage: %s ros_distro stack_name"%sys.argv[0]
        raise BuildException("Wrong number of parameters for ci devel script")
    else:
        ros_distro = sys.argv[1]
        stack = sys.argv[2]
        print "Working on distro %s and stacks %s"%(ros_distro, stack)

    workspace = os.environ['WORKSPACE']
    sourcespace = os.path.join('/tmp', str(datetime.datetime.now()).replace(' ','_').replace(':','.'))
    stackbuildspace = os.path.join(sourcespace, 'build_stack')
    os.makedirs(sourcespace)

    # Add ros to apt
    print "Add ros to apt sources"
    with open('/etc/apt/sources.list.d/ros-latest.list', 'w') as f:
        f.write("deb http://packages.ros.org/ros-shadow-fixed/ubuntu %s main"%os.environ['OS_PLATFORM'])
    call("wget http://packages.ros.org/ros.key -O %s/ros.key"%workspace)
    call("apt-key add %s/ros.key"%workspace)
    call("apt-get update")

    # install vcs tools
    print "Installing vcs tools"
    call("apt-get install mercurial subversion --yes")

    # Create rosdep object
    print "Create rosdep object"
    rosdep = RosDep(ros_distro)

    # parse the devel distro file
    print "Parsing devel yaml file for %s"%ros_distro
    f = urllib.urlopen('https://raw.github.com/ros/rosdistro/master/releases/%s-devel.yaml'%ros_distro)
    devel = yaml.load(f.read())['repositories']

    # download the stack from source
    print "Downloading stack %s"%stack
    if not stack in devel.keys():
        raise BuildException("Stack %s does not exist in devel distro file"%stack)
    conf = devel[stack]
    rosinstall = yaml.dump([{conf['type']: {'local-name': stack, 'uri': conf['url'], 'version': conf['version']}}], default_style=False)
    print "Rosinstall for stack %s:\n %s"%(stack, rosinstall)
    with open(workspace+"/stack.rosinstall", 'w') as f:
        f.write(rosinstall)
    print "Create rosinstall file for stack %s"%stack
    call("rosinstall %s %s/stack.rosinstall --catkin"%(sourcespace, workspace))

    # install the stack dependencies
    print "Get all stack dependencies"
    dependencies = get_dependencies(os.path.join(sourcespace, stack))
    if len(dependencies) > 0:
        print "Install all dependencies of stacks: %s"%(', '.join(dependencies))
        call("apt-get install %s --yes"%(' '.join([rosdep.to_apt(r) for r in dependencies])))

    # replace the CMakeLists.txt file for stacks that use catkin
    print "Removing the CMakeLists.txt file generated by rosinstall"
    os.remove(os.path.join(sourcespace, 'CMakeLists.txt'))
    os.makedirs(stackbuildspace)
    os.chdir(stackbuildspace)
    if 'catkin' in dependencies:
        print "Create a new CMakeLists.txt file using catkin"
        ros_env = get_ros_env('/opt/ros/%s/setup.bash'%ros_distro)
        call("catkin_init_workspace %s"%sourcespace, ros_env)
        call("cmake ..", ros_env)        
        ros_env = get_ros_env(os.path.join(stackbuildspace, 'buildspace/setup.bash'))
    else:
        print "Use the CMakeLists.txt file from the stack itself"
        ros_env = os.environ
        call("cmake ../%s"%stack, ros_env)

    # build stack
    print "Build stack %s"%stack
    call("make", ros_env)
    print "Test stack %s"%stack
    call("make run_tests", ros_env)

    # copy all test results
    copy_test_results(workspace, stackbuildspace)


if __name__ == '__main__':
    # global try
    try:
        main()
        print "Devel script finished cleanly"

    # global catch
    except BuildException as ex:
        print ex.msg

    except Exception as ex:
        print "Devel Test Failed. Check out the console output above for details."
        sys.exit(-1)
